//! Build script for the player binary.
//!
//! Two things happen here:
//!
//! 1. The icon and version resource are compiled into the executable so that
//!    Explorer, the taskbar and the file-association entries show a real icon
//!    instead of a generic one. An `.rc` file is generated into `OUT_DIR` with
//!    absolute paths, which sidesteps every "relative to what?" question that
//!    `rc.exe` otherwise raises.
//! 2. The FFmpeg runtime DLLs are copied next to the built executable, so
//!    `cargo run` works without touching `PATH` and a `cargo build` tree is
//!    immediately runnable.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Version stamped into the executable's VERSIONINFO resource.
const VERSION: (u16, u16, u16, u16) = (1, 0, 0, 0);

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let assets = manifest_dir
        .join("..")
        .join("..")
        .join("assets")
        .canonicalize()
        .unwrap_or_else(|_| manifest_dir.join("..").join("..").join("assets"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", assets.join("icon.ico").display());
    println!("cargo:rerun-if-changed={}", assets.join("app.manifest").display());
    println!("cargo:rerun-if-env-changed=FFMPEG_DIR");

    copy_ffmpeg_runtime();

    #[cfg(windows)]
    compile_windows_resources(&assets, &out_dir);
}

/// Emit the icon, the application manifest and the version block.
#[cfg(windows)]
fn compile_windows_resources(assets: &Path, out_dir: &Path) {
    let icon = assets.join("icon.ico");
    let manifest = assets.join("app.manifest");
    if !icon.exists() {
        println!(
            "cargo:warning=icon not found at {}; run scripts/make-icon.ps1",
            icon.display()
        );
        return;
    }

    let rc_path = out_dir.join("mvp_versatile_player.rc");
    let mut rc = String::new();
    rc.push_str("// Generated by mvp-player/build.rs — do not edit.\n");
    rc.push_str(&format!("1 ICON \"{}\"\n", escape(&icon)));
    if manifest.exists() {
        // 24 is RT_MANIFEST, 1 is CREATEPROCESS_MANIFEST_RESOURCE_ID.
        rc.push_str(&format!("1 24 \"{}\"\n", escape(&manifest)));
    }
    rc.push_str(&version_info());
    if fs::write(&rc_path, rc).is_err() {
        println!("cargo:warning=could not write the generated .rc file");
        return;
    }

    // `embed-resource` locates `rc.exe` through the Windows SDK registry keys,
    // which is the only reliable way when cargo is not run from a VS prompt. It
    // reports failure by printing to stderr rather than returning an error.
    let _ = embed_resource::compile(&rc_path, embed_resource::NONE);
}

#[cfg(not(windows))]
fn compile_windows_resources(_assets: &Path, _out_dir: &Path) {}

#[cfg(windows)]
fn version_info() -> String {
    let (a, b, c, d) = VERSION;
    let dotted = format!("{a}.{b}.{c}.{d}");
    format!(
        r#"
VS_VERSION_INFO VERSIONINFO
 FILEVERSION {a},{b},{c},{d}
 PRODUCTVERSION {a},{b},{c},{d}
 FILEFLAGSMASK 0x3fL
 FILEFLAGS 0x0L
 FILEOS 0x40004L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "080404b0"
        BEGIN
            VALUE "CompanyName", "MVP-Versatile-Player"
            VALUE "FileDescription", "MVP-Versatile-Player 多功能音视频与图片播放器"
            VALUE "FileVersion", "{dotted}"
            VALUE "InternalName", "mvp-versatile-player"
            VALUE "LegalCopyright", "GPL-3.0-or-later"
            VALUE "OriginalFilename", "mvp-versatile-player.exe"
            VALUE "ProductName", "MVP-Versatile-Player"
            VALUE "ProductVersion", "{dotted}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x804, 1200
    END
END
"#
    )
}

/// Copy the FFmpeg shared libraries next to the executable.
///
/// The import libraries are found at link time through `FFMPEG_DIR`, but the
/// DLLs are loaded at process start; without this, every `cargo run` and every
/// `cargo test` invocation would need `PATH` to be set up by hand.
fn copy_ffmpeg_runtime() {
    let Ok(prefix) = env::var("FFMPEG_DIR") else {
        println!("cargo:warning=FFMPEG_DIR is not set; FFmpeg DLLs will not be copied");
        return;
    };
    let bin = Path::new(&prefix).join("bin");
    if !bin.is_dir() {
        println!(
            "cargo:warning={} does not exist; FFmpeg DLLs will not be copied",
            bin.display()
        );
        return;
    }
    let Ok(out_dir) = env::var("OUT_DIR") else {
        return;
    };
    if let Some(target_dir) = profile_dir_from_out_dir(Path::new(&out_dir)) {
        let _ = copy_dlls(&bin, &target_dir);
        // Integration tests and binaries live in `deps/` and Windows searches
        // the executable's own directory first, so cover both.
        let _ = copy_dlls(&bin, &target_dir.join("deps"));
    }
}

fn copy_dlls(from: &Path, to: &Path) -> std::io::Result<()> {
    if !to.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("dll") {
            continue;
        }
        let destination = to.join(entry.file_name());
        // Skip the copy when the file is already current; a 170 MB FFmpeg
        // runtime should not be rewritten on every incremental build.
        if let (Ok(a), Ok(b)) = (fs::metadata(&path), fs::metadata(&destination)) {
            if a.len() == b.len() && b.modified().ok() >= a.modified().ok() {
                continue;
            }
        }
        let _ = fs::copy(&path, &destination);
    }
    Ok(())
}

/// `OUT_DIR` is `<target>/<profile>/build/<pkg>-<hash>/out`; walk back to
/// `<target>/<profile>`.
fn profile_dir_from_out_dir(out_dir: &Path) -> Option<PathBuf> {
    let mut current = out_dir;
    for _ in 0..3 {
        current = current.parent()?;
    }
    Some(current.to_path_buf())
}

#[cfg(windows)]
fn escape(path: &Path) -> String {
    path.display().to_string().replace('\\', "\\\\")
}
