//! Build script for the player binary.
//!
//! Two things happen here:
//!
//! 1. The icon and version resource are compiled into the executable so that
//!    Explorer, the taskbar and the file-association entries show a real icon
//!    instead of a generic one. An `.rc` file is generated into `OUT_DIR` with
//!    absolute paths, which sidesteps every "relative to what?" question that
//!    `rc.exe` otherwise raises.
//! 2. The FFmpeg runtime DLLs are copied next to the built executable, so
//!    `cargo run` works without touching `PATH` and a `cargo build` tree is
//!    immediately runnable.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Language every resource in this binary is declared under.
///
/// `rc.exe` falls back to a default taken from the build machine when the script
/// declares no language, which makes the shipped binary depend on who ran the
/// build. Declaring it keeps the resource tree deterministic and keeps it in step
/// with the language named by the version block below, so the two cannot
/// disagree.
///
/// `LANG_CHINESE` is 0x04 and `SUBLANG_CHINESE_SIMPLIFIED` is 0x02, which
/// combines into the 0x0804 used in the block name and in `Translation`.
const LANG_CHINESE_ID: u16 = 0x04;
const SUBLANG_CHINESE_SIMPLIFIED_ID: u16 = 0x02;

/// Codepage the version strings are written in; 1200 is Unicode.
const CODEPAGE_UNICODE: u16 = 1200;

/// The `0x0804` form of the language, as used in block names and translations.
#[cfg(windows)]
fn language_id() -> u16 {
    (SUBLANG_CHINESE_SIMPLIFIED_ID << 10) | LANG_CHINESE_ID
}

/// Version stamped into the executable's VERSIONINFO resource.
///
/// Taken from `CARGO_PKG_VERSION` rather than written out here, so the resource
/// Explorer shows and the string the About dialog prints cannot drift apart.
#[cfg(windows)]
fn version_quad() -> (u16, u16, u16, u16) {
    let raw = env::var("CARGO_PKG_VERSION").unwrap_or_default();
    // A pre-release suffix (`1.0.0-beta.1`) is not part of a `FILEVERSION`.
    let core = raw.split(['-', '+']).next().unwrap_or_default();
    let mut parts = core
        .split('.')
        .map(|part| part.trim().parse::<u16>().unwrap_or(0));
    (
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    )
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let assets = manifest_dir
        .join("..")
        .join("..")
        .join("assets")
        .canonicalize()
        .unwrap_or_else(|_| manifest_dir.join("..").join("..").join("assets"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", assets.join("icon.ico").display());
    println!("cargo:rerun-if-changed={}", assets.join("app.manifest").display());
    println!("cargo:rerun-if-env-changed=FFMPEG_DIR");

    copy_ffmpeg_runtime();

    #[cfg(windows)]
    compile_windows_resources(&assets, &out_dir);
}

/// Emit the icon, the application manifest and the version block.
#[cfg(windows)]
fn compile_windows_resources(assets: &Path, out_dir: &Path) {
    let icon = assets.join("icon.ico");
    let manifest = assets.join("app.manifest");
    if !icon.exists() {
        println!(
            "cargo:warning=icon not found at {}; run scripts/make-icon.ps1",
            icon.display()
        );
        return;
    }

    let rc_path = out_dir.join("mvp_versatile_player.rc");
    let mut rc = String::new();
    rc.push_str("// Generated by mvp-player/build.rs — do not edit.\n");
    // Must come before the resources it applies to, and must stay in step with
    // the language used by `version_info` below; see the constants above.
    //
    // Written as numbers rather than `LANG_CHINESE, SUBLANG_CHINESE_SIMPLIFIED`:
    // those names only exist once `winuser.h` has been included and this .rc has
    // no includes, so rc.exe rejected the line and every resource — icon,
    // manifest and version block alike — silently vanished from the executable.
    rc.push_str(&format!(
        "LANGUAGE {:#04x}, {:#04x}\n",
        LANG_CHINESE_ID, SUBLANG_CHINESE_SIMPLIFIED_ID
    ));
    rc.push_str(&format!("1 ICON \"{}\"\n", escape(&icon)));
    if manifest.exists() {
        // 24 is RT_MANIFEST, 1 is CREATEPROCESS_MANIFEST_RESOURCE_ID.
        rc.push_str(&format!("1 24 \"{}\"\n", escape(&manifest)));
    }
    rc.push_str(&version_info());
    if fs::write(&rc_path, rc).is_err() {
        println!("cargo:warning=could not write the generated .rc file");
        return;
    }

    // `embed-resource` locates `rc.exe` through the Windows SDK registry keys,
    // which is the only reliable way when cargo is not run from a VS prompt.
    //
    // The result used to be discarded, so a rejected `.rc` produced an executable
    // with no icon, no manifest and no version resource while the build still
    // reported success. The manifest carries the DPI and long-path settings, so
    // this is treated as required: a missing compiler fails the build too.
    if let Err(err) = embed_resource::compile(&rc_path, embed_resource::NONE).manifest_required() {
        panic!("could not compile {rc_path:?}: {err}. Is the Windows SDK (rc.exe) installed?");
    }
}

#[cfg(not(windows))]
fn compile_windows_resources(_assets: &Path, _out_dir: &Path) {}

/// The `VS_VERSIONINFO` block.
///
/// The resource is named `1`, spelled numerically, and that is load-bearing:
/// the usual `VS_VERSION_INFO VERSIONINFO` form only ends up as id 1 because
/// `VS_VERSION_INFO` is `#define`d to `1` in `winver.h`, and this `.rc` includes
/// no headers on purpose. Written as a bare word it becomes a *string* resource
/// name instead, and Windows' version APIs — which look the type up with
/// `MAKEINTRESOURCE(1)` — fail with `ERROR_RESOURCE_TYPE_NOT_FOUND`, leaving
/// Explorer's Details tab and `FileVersionInfo` with nothing to report.
#[cfg(windows)]
fn version_info() -> String {
    let (a, b, c, d) = version_quad();
    let dotted = format!("{a}.{b}.{c}.{d}");
    let lang = language_id();
    format!(
        r#"
// Must be id 1: see the note on `version_info` in build.rs before changing it.
1 VERSIONINFO
 FILEVERSION {a},{b},{c},{d}
 PRODUCTVERSION {a},{b},{c},{d}
 FILEFLAGSMASK 0x3fL
 FILEFLAGS 0x0L
 FILEOS 0x40004L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "{lang:04x}{CODEPAGE_UNICODE:04x}"
        BEGIN
            VALUE "CompanyName", "MVP-Versatile-Player"
            VALUE "FileDescription", "MVP-Versatile-Player 多功能音视频与图片播放器"
            VALUE "FileVersion", "{dotted}"
            VALUE "InternalName", "mvp-versatile-player"
            VALUE "LegalCopyright", "GPL-3.0-or-later"
            VALUE "OriginalFilename", "mvp-versatile-player.exe"
            VALUE "ProductName", "MVP-Versatile-Player"
            VALUE "ProductVersion", "{dotted}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x{lang:x}, {CODEPAGE_UNICODE}
    END
END
"#
    )
}

/// Copy the FFmpeg shared libraries next to the executable.
///
/// The import libraries are found at link time through `FFMPEG_DIR`, but the
/// DLLs are loaded at process start; without this, every `cargo run` and every
/// `cargo test` invocation would need `PATH` to be set up by hand.
fn copy_ffmpeg_runtime() {
    let Ok(prefix) = env::var("FFMPEG_DIR") else {
        println!("cargo:warning=FFMPEG_DIR is not set; FFmpeg DLLs will not be copied");
        return;
    };
    let bin = Path::new(&prefix).join("bin");
    if !bin.is_dir() {
        println!(
            "cargo:warning={} does not exist; FFmpeg DLLs will not be copied",
            bin.display()
        );
        return;
    }
    let Ok(out_dir) = env::var("OUT_DIR") else {
        return;
    };
    if let Some(target_dir) = profile_dir_from_out_dir(Path::new(&out_dir)) {
        let _ = copy_dlls(&bin, &target_dir);
        // Integration tests and binaries live in `deps/` and Windows searches
        // the executable's own directory first, so cover both.
        let _ = copy_dlls(&bin, &target_dir.join("deps"));
    }
}

fn copy_dlls(from: &Path, to: &Path) -> std::io::Result<()> {
    if !to.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("dll") {
            continue;
        }
        let destination = to.join(entry.file_name());
        // Skip the copy when the file is already current; a 170 MB FFmpeg
        // runtime should not be rewritten on every incremental build.
        if let (Ok(a), Ok(b)) = (fs::metadata(&path), fs::metadata(&destination)) {
            if a.len() == b.len() && b.modified().ok() >= a.modified().ok() {
                continue;
            }
        }
        let _ = fs::copy(&path, &destination);
    }
    Ok(())
}

/// `OUT_DIR` is `<target>/<profile>/build/<pkg>-<hash>/out`; walk back to
/// `<target>/<profile>`.
fn profile_dir_from_out_dir(out_dir: &Path) -> Option<PathBuf> {
    let mut current = out_dir;
    for _ in 0..3 {
        current = current.parent()?;
    }
    Some(current.to_path_buf())
}

#[cfg(windows)]
fn escape(path: &Path) -> String {
    path.display().to_string().replace('\\', "\\\\")
}
