# Downloads the FFmpeg development kit this project links against and writes the
# matching `.cargo/config.toml`.
#
# A *shared* build is required: the player links the import libraries and copies
# the DLLs next to the executable, so the archive must contain `include/`,
# `lib/*.lib` and `bin/*.dll`.
#
# The **n9.0 release branch** is used rather than `master`: master's headers
# already contain codec enum values that `ffmpeg-next 9.0.0` does not know about,
# which makes it fail to compile.
#
# Usage:  .\scripts\setup-ffmpeg.ps1 [-Destination C:\ffmpeg-dev] [-Version 9.0]

[CmdletBinding()]
param(
    [string] $Destination = 'C:\ffmpeg-dev',
    [string] $Version = '9.0'
)

$ErrorActionPreference = 'Stop'

$archive = "ffmpeg-n$Version-latest-win64-gpl-shared-$Version.zip"
$url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/$archive"
$zip = Join-Path $Destination $archive

New-Item -ItemType Directory -Force -Path $Destination | Out-Null

if (-not (Test-Path $zip)) {
    Write-Host "下载 FFmpeg $Version 开发包…" -ForegroundColor Cyan
    Write-Host "  $url"
    & curl.exe -L --retry 3 --retry-delay 2 -o $zip $url
    if ($LASTEXITCODE -ne 0) { throw "下载失败" }
} else {
    Write-Host "已存在 $zip，跳过下载" -ForegroundColor DarkGray
}

Write-Host '解压…' -ForegroundColor Cyan
Expand-Archive -Path $zip -DestinationPath $Destination -Force

$root = Get-ChildItem $Destination -Directory |
    Where-Object { $_.Name -like "ffmpeg-n$Version-*" } |
    Select-Object -First 1
if (-not $root) { throw "解压后找不到 FFmpeg 目录" }

# Sanity check: a build without headers or import libraries cannot be linked.
foreach ($needed in @('include', 'lib', 'bin')) {
    if (-not (Test-Path (Join-Path $root.FullName $needed))) {
        throw "这个 FFmpeg 包缺少 $needed 目录，需要 shared 构建"
    }
}
$libCount = (Get-ChildItem (Join-Path $root.FullName 'lib') -Filter *.lib).Count
if ($libCount -lt 5) {
    throw "lib 目录里只有 $libCount 个 .lib 文件，需要 MSVC 可用的导入库"
}

# libclang is required by ffmpeg-sys-next's bindgen step.
$libclang = $env:LIBCLANG_PATH
if (-not $libclang) {
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Programs\Python\Python312\Lib\site-packages\clang\native'),
        'C:\Program Files\LLVM\bin'
    )
    foreach ($candidate in $candidates) {
        if (Test-Path (Join-Path $candidate 'libclang.dll')) { $libclang = $candidate; break }
    }
}

$configPath = Join-Path (Split-Path -Parent $PSScriptRoot) '.cargo\config.toml'
$ffmpegDir = $root.FullName -replace '\\', '/'
$config = @"
# Generated by scripts/setup-ffmpeg.ps1 — see README.md.
#
# FFmpeg is linked directly (no side-car process) against the shared dev kit:
#   <root>/include  -> libav*/**/*.h
#   <root>/lib      -> avcodec.lib, avformat.lib, ... (MSVC import libraries)
#   <root>/bin      -> avcodec-*.dll, ...          (copied next to the exe)
#
# Every value uses ``force = false``, so an already-exported environment variable
# always wins over what is written here.

[env]
FFMPEG_DIR = { value = "$ffmpegDir", force = false }
LIBCLANG_PATH = { value = "$($libclang -replace '\\', '/')", force = false }
# ffmpeg-sys-next's hwcontext shim predates a couple of CUDA handle types that
# FFmpeg 9's ``hwcontext_cuda.h`` now exposes. Supplying them as opaque clang
# macros lets bindgen finish; the player never touches CUDA itself.
BINDGEN_EXTRA_CLANG_ARGS = { value = "-DCUarray=void* -DCUDA_ARRAY3D_DESCRIPTOR=void*", force = false }
"@
Set-Content -Path $configPath -Value $config -Encoding UTF8

Write-Host ''
Write-Host '完成。' -ForegroundColor Green
Write-Host ("  FFmpeg : {0}" -f $root.FullName)
Write-Host ("  libclang: {0}" -f $(if ($libclang) { $libclang } else { '未找到 —— 请 pip install libclang 或安装 LLVM' }))
Write-Host ("  配置   : {0}" -f $configPath)
Write-Host ''
Write-Host '接下来可以运行: .\scripts\dev.ps1 build --release -p mvp-player' -ForegroundColor DarkGray
